spring.application.name=Beta-solutions
spring.sql.init.mode=never
spring.datasource.url=jdbc:mysql://localhost:3306/betasolutions?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Glostrup114!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
