DELETE FROM Sub_Tasks_Skills;
DELETE FROM Profiles_Sub_Tasks;
DELETE FROM Sub_Tasks;
DELETE FROM Tasks_Skills;
DELETE FROM Profiles_Tasks;
DELETE FROM Tasks;
DELETE FROM Project_Skills;
DELETE FROM Profiles_Projects;
DELETE FROM Projects;
DELETE FROM Profiles_Skills;
DELETE FROM Profiles;
DELETE FROM Skills;

ALTER TABLE Skills ALTER COLUMN id RESTART WITH 1;
ALTER TABLE Profiles ALTER COLUMN id RESTART WITH 1;
ALTER TABLE Projects ALTER COLUMN id RESTART WITH 1;
ALTER TABLE Tasks ALTER COLUMN id RESTART WITH 1;
ALTER TABLE Sub_Tasks ALTER COLUMN id RESTART WITH 1;